# .air.toml
root = "."

tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  bin = "mp/main"
  full_bin = "false"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "node_modules"]
  exclude_file = []
  follow_symlink = true
  log = "build.log"

[log]
  time = true
  leve = "debug"

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"