# Use full Go image with tools and git
FROM golang:1.24

WORKDIR /app

# Install air for live reloading
# RUN go install github.com/air-verse/air@v1.62.0

# Copy go mod files first and download dependencies (for caching)
COPY go.mod go.sum ./
RUN go mod download

# Copy all source files
COPY . .
# COPY .air.toml ./
# COPY airconfig.toml ./

# Expose the application port
EXPOSE 8080

# Default command to run air (watch for changes and reload)
# CMD ["air"]
# CMD ["air", "-c", ".air.toml"]
# CMD ["air", "-c", "airconfig.toml"]
CMD ["go", "run", "./cmd/main.go"]
