# Use full Go image with tools and git
FROM golang:1.25

ENV ENV=development

WORKDIR /app

# Install air for live reloading
# RUN go install github.com/air-verse/air@v1.62.0

# Copy go mod files first and download dependencies (for caching)
COPY go.mod go.sum ./
RUN go mod download

# Copy all source files
# COPY . . // commenting out to avoid every time rebuilding the image after any code change in dev environment
# COPY .air.toml ./
# COPY airconfig.toml ./

# Expose the application port
EXPOSE 8080

# Default command to run air (watch for changes and reload)
# CMD ["air"]
# CMD ["air", "-c", ".air.toml"]
# CMD ["air", "-c", "airconfig.toml"]


# let docker-compose.dev.yml handle the command to run the server and workers
# CMD ["go", "run", "./cmd/server/main.go"]
# CMD ["go", "run", "./cmd/workers/main.go"]