apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: notifier
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: go-notifier
data:
  rabbitmq.conf: |
    # Disable built-in metrics collector to avoid duplicating Prometheus metrics.
    management_agent.disable_metrics_collector = true