production:
  dynamic_queue: false
  queues:
    - email_delivery
    - email_delivery_dlq
    - email_delivery_retry
development:
  dynamic_queue: false
  queues:
    - email_delivery
    - email_delivery_dlq
    - email_delivery_retry
test:
  dynamic_queue: false
  queues:
    - email_delivery
    - email_delivery_dlq
    - email_delivery_retry